### PR TITLE
Dat 16 hierarchy

### PR DESCRIPTION
**Pull request by hnnesv**
DAT-16

### CODE REVIEW

**Comment by rcrichton** [comment]
@hnnesv some initial comments. I don't think this handles the case when there are multiple root orgunits. At least in my testing it didn't. Also, I'm not seeing the '>' in front of the orgunit until I click on it. I'm also seeing some lint errors, run `npm test` to see these. I'l go through the code now as well.

**Comment by rcrichton** [comment]
Otherwise, the code looks good. It would just be good to have some basic tests on some of the exported modules.

**Comment by hnnesv** [comment]
Hey @rcrichton oh I didn't realize you could even have multiple root orgunits. Is datim using that?

I'll have to think of a solution for the '>'. The problem is I'll only know if a orgunit has children when you click on it; so that was intentional.

**Comment by rcrichton** [comment]
I believe mutiple roots are used in DATIM as it serves all pepfar funded sites. I believe their top levels are the continents, so, they will most likely be managing atleast an 'Africa' and 'Asia' root.

Maybe you need to load an orgunit and it's children each time it is displayed? The UI would then also be ultra responsive as well.

**Comment by hnnesv** [comment]
Aah ok cool.

Well I was trying avoid that in case an orgunit has a lot of children (it would be a transaction for each of them). But maybe I'm just prematurely optimizing; lemme try it and see.

**Comment by rcrichton** [comment]
Yeah, I don't see a way around it unfortunately.

**Comment by rcrichton** [comment]
Closing as this in now contained in #4

**Pull request closed without merging**
